### ISSUE TITLE
No app name specified

### ISSUE THREAD

**Issue by pierreozoux** [pellaeon/registration#15]
Hi!

When I follow instruction here:

https://apps.owncloud.com/content/show.php/Registration?content=170608

When I enable the app in the admin panel, I get the following error:
```
No app name specified
```

fix: mv registration-0.0.4/ registration

**Comment by pellaeon** [comment]
That name was automatically generated by GitHub, I will re-upload the app directly to apps.owncloud.com , thanks for the report.

By the way, if you know how to use git, I think it should be more convenient to just clone this repository, it makes upgrade easier too.

**Comment by pierreozoux** [comment]
Ok great, it was just a little hint :)

< off topic >
What is the best way to maintain apps? Because I manage dozens of owncloud instance as an [IndieHosters](https://indiehosters.net) and this is a pain.

When I do upgrades, it deactivates apps from the users. Then they reactivate them, but they are broken, I need to find the latest version.

This is not scalable :/

Why isn't there any package management? Why not using composer?
Do you have an idea to solve this issue?
Actually, yesterday, speaking with a friend we though about git.
For your repo, is master alsways 'bug free' not like a development branch I mean.
Or maybe I can/should use the tags.

I'm just curious how to deal with that, if you have hints, I'd be glad!

Thanks a lot for your work!

Best,

Pierre

< / off topic >

**Comment by pellaeon** [comment]
For my own ownCloud instance I always manage apps and ownCloud itself using git. I don't care much about releases, I just pull from master branch from time to time, there is normally not much of an issue, most upgrade went smoothly. Sometime it breaks I'll just upgrade the apps too then it'll work. The mater branch of owncloud core is quite stable in my opinion.

For the registration app, yes, at least I'd make sure master branch will work on my machine.
At this stage releases is not much of a difference with master branch becasue both are quite untested. It might change though, I might introduce more sophisticated testing so that I can do before release.

**Comment by pierreozoux** [comment]
Thanks for your input!
