### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Oriann** [pellaeon/registration#171]
Is possible to attach translations into code ?
I need czech language button for registrators and info texts.
I can help translate to czech if needed, just point me to the right direction.

**Comment by pellaeon** [comment]
Translations are located under `l10n/` folder. Thanks

**Comment by AlvinZhn** [comment]
> Translations are located under `l10n/` folder. Thanks

Seems like error message from password_policy can't be translated. The error messages translate well in password reset page, but it only show English error message if i enter a weak password during my registration.

I got `Password is among the 1,000,000 most common ones. Please make it unique.` rather than a translated one.

Cloud you please tell me how to solve this?

**Comment by obourdon** [comment]
@AlvinZhn I am not able to find this string anywhere is it really in the registration app or in owncloud core ?

**Comment by pellaeon** [comment]
I can confirm that `Password is among the 1,000,000 most common ones. Please make it unique.` this string is not in the registration app.

Closing this issue because the original question has been answered.
