### ISSUE TITLE
Feature suggestion: do not check "A user has already taken this email"

### ISSUE THREAD

**Issue by vmalep** [pellaeon/registration#176]
### Steps to reproduce
1. From the Login page, click on "Register"
2. Enter the email address
3. From the email, click on the link and create the new user.
4. Repeat from 1 with the same email address without error message ("A user has already taken this email")

### Expected behaviour
Tell us what should happen

Registration app should offer the option not to check if an email is already taken (in order to allow someone with an email to create an account for someone else having no email address).

### Actual behaviour
Tell us what happens instead

In case the email was already used, Registration does not allow the link to be sent.

### Server configuration
**Operating system**:

Ubuntu 18.04

**Nextcloud version:** (see Nextcloud admin page)

15.0.7

**Comment by pellaeon** [comment]
I think to create account for someone else having no email address is not an use case that the app is going to support. It sounds like you're an admin because you're requesting this option for you to set. But if you're an admin already, you should be able to directly create an account without email.
