### ISSUE TITLE
Default User Group doesn't work

### ISSUE THREAD

**Issue by PaperlessPioneers** [pellaeon/registration#201]
Hey there,

the selected Usergroup to put in new registration user doesn't work ( i mean this https://share.nafdo.de/8LuJAXmP ).

He only adds new users to the first Group he found in the system.

Thanks !

**Comment by pellaeon** [comment]
Please strictly follow the issue template, otherwise I do not have required information to fix the issue.

**Comment by aixzellent** [comment]
We have the same issue...

Steps to reproduce:
Install Registration Plugin
Configure Plugin with limit to groups: <myguestgroup>
Register a new user <myguestuser1> using the registration plugin

Expected behaviour:
<myguestuser1> associated to <myguestgroup>

Actual behaviour
<myguestuser1> associated to no group

Server configuration
Operating system:
Ubuntu 18.04 LTS

Web server:
apache2, 2.4.29

Database:
mysql, 5.7.31

PHP version:
7.2.24

Nextcloud version: (see Nextcloud admin page)
19.0.1

Updated from an older Nextcloud/ownCloud or fresh install:
fresh install

**Comment by 2fst4u** [comment]
This is still broken. Typing a user group fills the box, and the page says it has saved, but after browsing away from the registration settings and coming back it doesn't keep the setting.
