### ISSUE TITLE
can`t install plugin in version 0.2.3 on NC 11

### ISSUE THREAD

**Issue by humbug83** [pellaeon/registration#55]
hi,

i can`t install the plugin on updated nexcloud 11 on my raspy. It says that the reqiured dependency isn`t met: 

**Following databases are supported: sqlite, mysql**

I`m running myqsl-server version 5.5, so i don`t see a reason why it shouldn`t work.
Any idea?

Thx in advance

edit:
with version 0.2.2 it works. Only had to add following line:
<nextcloud min-version="9.0" max-version="12"/>, so installation won`t stop with message that version is too low.

**Comment by pellaeon** [comment]
I think it's due to this line added here: https://github.com/pellaeon/registration/blob/master/appinfo/info.xml#L15

the check is done within Nextcloud, all the app developers do is to specify dependencies, so looks like they have a bug.

Can you provide the full version string of your mysql server? use `mysql -v`

**Comment by humbug83** [comment]
Hi, thx for the reply...

The exactly server version is:
Server version: 5.5.53-0+deb8u1 (Raspbian)

I also tried to change the added line in info.xml to "needed server version 5.4" to check if it`s working afterwards but also no success. So, as i said, i took the old version and added the line with the needed nextcloud-version and it works so far :)

So, it`s no big problem for me, just wanted to add the issue here and share my "solution" with others.
