### ISSUE TITLE
ownCloud 10 compatibility

### ISSUE THREAD

**Issue by cdamken** [pellaeon/registration#71]
Hi @pellaeon,

For now is only running in 9.1, do you plan to do the app for oC10?

Greetings.

**Comment by gmdxrillex** [comment]
edit info.xml from <owncloud min-version="9.0" max-version="9.2"/> to <owncloud min-version="9.0" max-version="10"/> you might get an error but it still works

**Comment by kesavarajaphp** [comment]
Hi @pellaeon,

Even if i change the version to 10.0.2 , the app seems doesn't work. 
I got the error "registration can't be enabled since it is not installed.". Please help me to resolve this issue
Regards, 
Kesav

**Comment by happicamper** [comment]
Hi @kesavarajaphp,
Are you still experiencing this issue? I've tried downloading the application, placed it on /core/apps/ with right permissions, and editing the info.xml then everything worked.

**Comment by motorious719** [comment]
Hi @happicamper  I am still having issues getting the app to work on 10.0.2...

I extracted the folder from the zip 'registration master' and moved it to /var/www/owncloud/apps as well as /var/www/owncloud/core/apps.  Restarted apache service '/etc/init.d/apache2 restart' and it's not working.  Both locations have root:root ownership and 755 permisisons.  The info.xml has:

                <owncloud min-version="9.0" max-version="11"/>

My /var/log/owncloud.log shows:
{"reqId":"fy6pGoyZcmYu9audV4ps","level":3,"time":"2017-09-02T16:36:52-06:00","remoteAddr":"<gateway_IP_redacted>","user":"<admin_username_redacted>","app":"core","method":"POST","url":"\/owncloud\/index.php\/settings\/ajax\/uninstallapp.php","message":"can't remove app registration. It is not installed."}

{"reqId":"tMqOc7zg1GwcpXLlSe0g","level":3,"time":"2017-09-02T16:36:54-06:00","remoteAddr":"<gateway_IP_redacted>","user":"<admin_username_redacted>","app":"PHP","method":"POST","url":"\/owncloud\/index.php\/settings\/ajax\/enableapp.php","message":"Argument 1 passed to OC\\App\\DependencyAnalyzer::analyze() must be of the type array, null given, called in \/var\/www\/owncloud\/lib\/private\/legacy\/app.php on line 1217 and defined at \/var\/www\/owncloud\/lib\/private\/App\/DependencyAnalyzer.php#53"}

{"reqId":"tMqOc7zg1GwcpXLlSe0g","level":3,"time":"2017-09-02T16:36:54-06:00","remoteAddr":"<gateway_IP_redacted>","user":"<admin_username_redacted>","app":"PHP","method":"POST","url":"\/owncloud\/index.php\/settings\/ajax\/enableapp.php","message":"Argument 2 passed to OC\\App\\DependencyAnalyzer::analyzeOC() must be of the type array, null given, called in \/var\/www\/owncloud\/lib\/private\/App\/DependencyAnalyzer.php on line 67 and defined at \/var\/www\/owncloud\/lib\/private\/App\/DependencyAnalyzer.php#293"}
{"reqId":"tMqOc7zg1GwcpXLlSe0g","level":3,"time":"2017-09-02T16:36:54-06:00","remoteAddr":"192.168.0.2","user":"knight","app":"core","method":"POST","url":"\/owncloud\/index.php\/settings\/ajax\/enableapp.php","message":"registration can't be enabled since it is not installed."}

Checked the lines in the php files mentioned but I have no idea what I'm looking for or at really since I'm not a programmer.

Any ideas?

**Comment by motorious719** [comment]
Hi @happicamper,  I am having issues installing on owncloud 10.0.2

I extracted the folder from the zip 'registration master' and moved it to /var/www/owncloud/apps as well as /var/www/owncloud/core/apps. Restarted apache service '/etc/init.d/apache2 restart' and it's not working. Both locations have root:root ownership and 755 permisisons. The info.xml has:

            <owncloud min-version="9.0" max-version="11"/>

My /var/log/owncloud.log shows:
{"reqId":"fy6pGoyZcmYu9audV4ps","level":3,"time":"2017-09-02T16:36:52-06:00","remoteAddr":"<gateway_IP_redacted>","user":"<admin_username_redacted>","app":"core","method":"POST","url":"/owncloud/index.php/settings/ajax/uninstallapp.php","message":"can't remove app registration. It is not installed."}

{"reqId":"tMqOc7zg1GwcpXLlSe0g","level":3,"time":"2017-09-02T16:36:54-06:00","remoteAddr":"<gateway_IP_redacted>","user":"<admin_username_redacted>","app":"PHP","method":"POST","url":"/owncloud/index.php/settings/ajax/enableapp.php","message":"Argument 1 passed to OC\App\DependencyAnalyzer::analyze() must be of the type array, null given, called in /var/www/owncloud/lib/private/legacy/app.php on line 1217 and defined at /var/www/owncloud/lib/private/App/DependencyAnalyzer.php#53"}

{"reqId":"tMqOc7zg1GwcpXLlSe0g","level":3,"time":"2017-09-02T16:36:54-06:00","remoteAddr":"<gateway_IP_redacted>","user":"<admin_username_redacted>","app":"PHP","method":"POST","url":"/owncloud/index.php/settings/ajax/enableapp.php","message":"Argument 2 passed to OC\App\DependencyAnalyzer::analyzeOC() must be of the type array, null given, called in /var/www/owncloud/lib/private/App/DependencyAnalyzer.php on line 67 and defined at /var/www/owncloud/lib/private/App/DependencyAnalyzer.php#293"}

{"reqId":"tMqOc7zg1GwcpXLlSe0g","level":3,"time":"2017-09-02T16:36:54-06:00","remoteAddr":"<gateway_IP_redacted>","user":"<admin_username_redacted>","app":"core","method":"POST","url":"/owncloud/index.php/settings/ajax/enableapp.php","message":"registration can't be enabled since it is not installed."}

Checked the lines in the php files mentioned but I have no idea what I'm looking for or at really since I'm not a programmer.

Any ideas?

**Comment by motorious719** [comment]
nevermind...pbkac issue had to rename the app folder from: 
/var/www/owncloud/apps/registration-master 
to 
/var/www/owncloud/apps/registration

pbkac means problem between keyboard and chair like an id10t error ;-)

**Comment by happicamper** [comment]
@motorious719 And now working? 😄 
I thought your problem earlier exist because of ownership because apache should hold those files.
👍  For elaborating pbkac cuz I don't really have an idea what it means.

**Comment by cdamken** [comment]
I just tested the app with 10.0.4 and work fine.
